### ISSUE TITLE
Request to update or rethink packages to build parallelism with updated packages in distro repositories

### ISSUE THREAD

**Issue by diqidoq** [KXStudio/Repository#100]
Since some packages provided by KXStudio repositories are more recently updated than the ones provided by some KXStudio supported Linux distro repositories, what is really great(!), it is recommended to not fall back with others in the same time IMHO. Some other packages provided by KXStudio are older than the updated packages provided by the Linux distro repositories. This can cause a lot of confusion and problems. Additionally updating the system can cause overwrites of newer packages by older packages from the KXStudio repositories.

One possible reason can be the KXstudio own versioning using the leading integer bit 1:xxx or 2:xxx, maybe causing that some distro repository management thinks to get more recent versions from a package there, e.g. qjackctl 2:0.4.1-kxstudio which is actually qjackctl 0.4.1 will be installed and overwrites Debians packaged version already installed 0.4.4 including a possible chance to override conf files. These conf files are often very complicated to set up and it can be quite frustrating to loose them. Also some newer packages are required by other packages or self compiled audio packages from source code.

I see 2 possible solutions here:

 1. Change the versioning and update policy of KXstudio to not conflict with newer packages already installed despite of exceptions, when certain older versions are required. But in the last case there should be a warning and choise.
 2.  Do not repackage audio packages which are available and most commonly updated in the Linux distro repositories to save time and trouble, if this is possible.

**Comment by diqidoq** [comment]
From what I have been hit by using Debian 9, I can say this affects following newer packages in Debian repos atm:

 + qjackctl -- 0.4.1 overwrites 0.4.4
 + swh-lv2 -- 1.0.15 overwrites 1.0.16
 + tap-plugins -- 0.7.2 overwrites 0.7.3-2
 + caps -- 0.9.23 overwrites 0.9.24-4
 + wah-plugins -- 0.1.0-1 overwrites 0.1.0-4
 + qsampler -- 0.3.1 overwrites 0.4.2
 + amb-plugins -- 0.8.1-4 overwrites 0.8.1-7
 + and some more ... (to be continued ...)

**Comment by falkTX** [comment]
The reason for the version bump in kxstudio's packages is that debian sometimes builds things unoptimized, not optimized enough, with debug on or with missing features.
For audio, we want the binaries as much optimized as possible (SSE2 + fast-math is important to avoid denormals), and to hide and strip all symbols and unused code (making symbol clashing in plugins less likely to happen)

Right now I don't have as much time for the kxstudio repositories as I used to have before, so things are getting a bit behind.

Note that 1.16-1 vs 1.16-2 does not really make a difference.
The -2 bump in debian is likely just a small text or package style update.

**Comment by diqidoq** [comment]
Thanks for taking the time @falkTX ... so all KXStudio provided packages are differently optimized than the ones in the Debian repos? If so, shouldn't we think about to build forces for frequently packaging? It shouldn't depend on your time table if something sensitive like this can possibly break one day.

**Comment by falkTX** [comment]
There's different optimizations yes.
But also kxstudio packages are built with static libs, so that a single deb works for every single distro.
(and some build options are different too)

There's no escaping issues if you run Debian Testing/Sid though.
We have to let Debian do their changes, then adapt for the stable release.

I'm still running an Ubuntu 14.04 based system.
This is the main reason for the repos to exist, to have new packages for older distros.
I don't want to use a testing distro, but want to have my audio stuff updated.

**Comment by falkTX** [comment]
I am dropping support for a LOT of packages (basically all non-plugins) in order to keep things simple and easier to update.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back

This will reduce the number of packages that get into this situation.
I think this is a good middle ground, and will leave it at that
