### ISSUE TITLE
Musescore 2.1

### ISSUE THREAD

**Issue by alepeccioli** [KXStudio/Repository#106]
New upstream Musescore. Thanks!

**Comment by mirabilos** [comment]
There are official MuseScore 2 and 3 builds in Debian and Debian backports now (for stretch and older, I am providing updates in my personal package repository because backports for those are now closed given stretch entered the LTS phase).

The same package versions are also available for various *buntu releases in the official PPAs:
https://launchpad.net/~mscore-ubuntu/+archive/ubuntu/mscore3-stable/+packages and https://launchpad.net/~mscore-ubuntu/+archive/ubuntu/mscore-stable/+packages

The very same packages are also rebuilt under KDE neon (different Qt versions): see https://musescore.org/en/handbook/3/install-linux#KDEneon for instructions there.

**Comment by wolftune** [comment]
Musescore is no longer part of KXStudio repos at all, but thanks for posting that update here. I used to do that KDEneon approach myself, but something went wrong (don't recall why and when), and I'm just using the AppImage now. I'd love if the Neon option was reliably kept updated and was working smoothly with Jack etc, AppImage is kinda annoying but not so bad

**Comment by mirabilos** [comment]
Aaron Wolf dixit:

>I'd love if the Neon option was reliably kept updated

I’m trying to keep it in sync with what’s in Debian. The OpenSuSE
buildservice is sometimes a bit tricky to work with or plain buggy
but, normally, the packages there should function.

In Debian I don’t always package the latest upstream version. This
has to do with Debian’s release cycles, as well as plain maintainer
time/effort, but also because upstream releases sometimes are banana
software or plain introduce regressions. I’ve backported about one
hundred bugfixes from the later releases, however I’ll look into 3.6
later (after Debian 11 will be released) although, first, I’ll need
to figure out ways to work around the massive UX regressions wrt.
note input 3.3 introduced ☹ this seems it needs code patches, though
upstream may at least commit them if someone makes them.

As things are now, 3.6 scores will work with 3.2.3, and I even
backported the 3.3+ plugin fixes and some new functions, so many
more plugins work.

> and was working smoothly with Jack etc
>AppImage is kinda annoying but not so bad

As far as I know, the distro packages always work with JACK, whereas
the AppImages don’t. That being said I normally don’t run JACK, only
when needed (i.e. for Jamulus, which I’ve not yet really used) but
that’s what user feedback I got.

(The AppImages are also probably illegal to distribute, but that’s
not my call.)

**Comment by wolftune** [comment]
FWIW, the Appimages right from Musescore.org work with Jack just fine
