### ISSUE TITLE
Package request: Firefox built with --enable-jack

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#117]
See http://www.zamaudio.com/?p=1580

To make things more complex, many of us actually want Firefox with --enable-jack *and* the plasmazilla stuff. I sent the plasmazilla folks a message asking if they'd offer builds with `--enable-jack`…

**Comment by falkTX** [comment]
the plasma/kde patch complicates things.
with kde, we can only build for 1 specific system at a time.

I say, if nothing happens after october, when the new 18.04 KX ISO development starts, I'll try to do kde-patch + jack firefox builds, for 18.04.

**Comment by wolftune** [comment]
How specific is specific? Is Neon different from Kubuntu when based on the same Ubuntu release in this case?

**Comment by falkTX** [comment]
An application built against a KDE version is very likely to not work on another.
Since they have their own entire desktop, they don't care about backwards compatibility of binaries.
(which makes sense for a project like KDE)

For KXStudio this would mean a different build for each Ubuntu version, and not being able to do generic Debian builds.
So if this happens, we'll have to pick a system to be supported and stick with it.

**Comment by falkTX** [comment]
maybe I was not clear enough.
I do want the plasmazilla stuff myself, and also the jack support.
but building that for each ubuntu version, plus neon, it's too much work.

I plan to make a new ISO for 18.04, and I will make it my main system (development to begin in november when Ubuntu opens the new DEV cycle). So if up until that point we don't have plasmazilla + jack builds somewhere, I will do them myself for Ubuntu 18.04 systems.
Not for neon though, whatever KDE5 version ends up being in 18.04 it's the one we will use.
Packages for it will be frozen, which is good for patching things.
Things that upstream KDE fixes in new versions we can backport as needed.

**Comment by markc** [comment]
If you add the JACK support patches to Firefox would you mind looking into the option (about:config) of disabling auto-connect to capture and playback ports please as it renders the entire FF+Jack package useless when used with ie; Ardour for mixing. For instance, every time a Youtube video is played (even paused I think) it will auto reconnect to the playback ports bypassing whatever Ardour track that a patchbay might have set up for it. Even though the FF cpu usage was nearly half compared to using the pulseaudio bridge I had to abandon my FF+Jack tests because I could not disable the auto-connecting to playback ports. VLC has an option to disable this behavior otherwise it would also be useless with any Jack mixer.

**Comment by falkTX** [comment]
Some people say exactly the opposite - ie, the jack output is not useful at all without the auto-connect.
I feel like people don't really know about jack2 self-connect mode option.. it exists precisely for situations like this, so that applications cannot connect themselves to other random ports.

**Comment by markc** [comment]
The default behavior atm is to auto-connect to the system playback ports and that is fine and suits most people for most situations. I was suggesting to enable an option (ie; perhaps via about:config) to disable that default behavior for those of us with more sophisticated needs otherwise a JACK enabled Firefox is almost useless when used with Ardour.

Perhaps I am one of those people that "don't really know about jack2 self-connect mode". Are you saying that I can tell jack2 to disallow FF+Jack output ports from auto-connecting to any hardware playback ports?

**Comment by falkTX** [comment]
An option would be best, I agree. You should request the feature upstream.

And yes, the no-self-connect mode does exactly what you're describing here.
from `jackd -h`:

>                [ --autoconnect OR -a <modechar>]
>                  where <modechar> is one of:
>                    ' ' - Don't restrict self connect requests (default)
>                    'E' - Fail self connect requests to external ports only
>                    'e' - Ignore self connect requests to external ports only
>                    'A' - Fail all self connect requests
>                    'a' - Ignore all self connect requests

The 'e' option is what you want here.
Note that with this, ardour will not be able to connect to system inputs/outputs either.
But you can use an external patchbay application to make those connections for you.

**Comment by milasudril** [comment]
See also my comment on the port connection issue: https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=783733 . What do you think is the best solution to the problem?

**Comment by falkTX** [comment]
building firefox is not trivial, basically "won't do" for this ticket.
and tbh, the jack support there is not great
