### ISSUE TITLE
Update wineasio code

### ISSUE THREAD

**Issue by falkTX** [KXStudio/Repository#126]
New version at https://github.com/jhernberg/wineasio

**Comment by aljelly** [comment]
I built both the 32-bit and 64-bit version of these from the current master. It was built on elementary OS (based on Ubuntu 16.04) using the wine-devel 3.2 libraries. Would you be interested in the built binaries? I put them in my [public Keybase folder](https://keybase.pub/aljelly/linux%20related/wineasio%200.9.2/).

(**64-bit works!** Also it seems to now correctly report total latency to the DAW, taking periods/buffers into account.)

**Comment by isaiah36** [comment]
Hi aljelly,

Is it possible to install your version in 18.04 with the default wine? Could you give me a quick how-to? I understand this site is for developers, not users, but I am just taking a long shot. Thanks!

**Comment by falkTX** [comment]
You can install the wineasio package in 18.04, yes.
Do you know how to enable the kxstudio repos? Do that first, update all software and install the package called "wineasio".

**Comment by isaiah36** [comment]
Thanks for the reply, falkTX. I do have the repos, but when I try to install wineasio it warns me that the default wine will be removed. This worries me because I have another, non audio wine app that is critical to my work. If I do go ahead with the install it throws up a failure error, like "You have held packages".

**Comment by aljelly** [comment]
I don't know if it works on 18.04, but you can try it. To install it (copy and paste in terminal):

```bash
winepath="/opt/wine-devel" # Change to where wine is installed, no slash at end
wget -P "/tmp/wineasio_tmp/32bit/" https://aljelly.keybase.pub/linux%20related/wineasio%200.9.2/32%20bit/wineasio.dll.so
wget -P "/tmp/wineasio_tmp/64bit/" https://aljelly.keybase.pub/linux%20related/wineasio%200.9.2/64%20bit/wineasio.dll.so
sudo mv "/tmp/wineasio_tmp/32bit/wineasio.dll.so" $winepath/lib/wine/
sudo mv "/tmp/wineasio_tmp/64bit/wineasio.dll.so" $winepath/lib64/wine/
sudo chmod ga+r $winepath/lib/wine/wineasio.dll.so
sudo chmod ga+r $winepath/lib64/wine/wineasio.dll.so
regsvr32 wineasio.dll
wine64 regsvr32 wineasio.dll
```

<details>
<summary>If you have Keybase</summary>

Use this script instead:
```bash
winepath="/opt/wine-devel" # Change to where wine is installed, no slash at end
mkdir -p /tmp/wineasio_tmp/32bit/
mkdir -p /tmp/wineasio_tmp/64bit/
cp "/keybase/public/aljelly/linux related/wineasio 0.9.2/32 bit/wineasio.dll.so" /tmp/wineasio_tmp/32bit/
cp "/keybase/public/aljelly/linux related/wineasio 0.9.2/64 bit/wineasio.dll.so" /tmp/wineasio_tmp/64bit/
sudo mv "/tmp/wineasio_tmp/32bit/wineasio.dll.so" $winepath/lib/wine/
sudo mv "/tmp/wineasio_tmp/64bit/wineasio.dll.so" $winepath/lib64/wine/
sudo chmod ga+r $winepath/lib/wine/wineasio.dll.so
sudo chmod ga+r $winepath/lib64/wine/wineasio.dll.so
regsvr32 wineasio.dll
wine64 regsvr32 wineasio.dll
```
See [this page (the Security section)](https://keybase.io/docs/kbfs/keybase.pub) as for why.
</details>

---

What this script does is download the 32-bit and 64-bit versions of the WineASIO libraries I built to a folder in /tmp/, moves them (with sudo) to the location of Wine's lib folders (which you will have to check is correct), sets the necessary file permissions (with sudo), and then registers them with Wine.

You'll need to update the `winepath` variable in that script to where your Wine installation is located.
- If you installed Wine from WineHQ, you'll find it in the /opt/ folder
  - If you're using WineHQ's wine-devel, you won't have to make any changes to the script.
- If you installed Wine from your distro's provided packages, I'm not sure where the correct library locations would be for them, for Ubuntu/Debian it might be /usr/lib/wine/ and /usr/lib64/wine/, you could try running `locate ntdll.dll.so` to find/confirm this. If it is, change the variable to `winepath="/usr"`

If it doesn't work on 18.04, you can try building WineASIO yourself, but the process is a bit involved. You need some packages like the Wine libraries and mingw-w64 (not sure if Wine source code is also required), and you'll need the 32-bit version of these as well if you're on 64-bit, but there may be some other packages as well that you need. You will need to build twice for both the 32-bit and 64-bit versions. Unfortunately I don't exactly remember what I installed to build it (and it was a bit of a trip down a rabbit hole to find these packages to successfully build it) or what commands I used, which is why I put the compiled libraries up for others. If I do it again I'll document what I needed.

**Comment by isaiah36** [comment]
Thanks aljelly! Both wine and wine64 are located in /usr/lib/wine so I decided to try it with 32bit only. The script ran. I can see wineasio.dll.so in place. But it ends with "regsvr32: Failed to load DLL 'wineasio.dll'".

I don't know what Keybase is, or whether I have it.

**Comment by FilipeCSnuk** [comment]
why are you downloading binaries from random places?
No need for anything fancy, I guess this is just a matter of package conflicts and dependencies that need to be adapted.

You can just download the debs and extract them, skipping install.
Like this:
```
apt-get download wineasio-amd64
apt-get download wineasio-i386
sudo dpkg -x wineasio-amd64*.deb /
sudo dpkg -x wineasio-i386*.deb /
```

**Comment by aljelly** [comment]
I should've asked these first, but:
- What version of Wine are you using? Running `wine --version` will tell you.
- Are you using a 32-bit or 64-bit OS?
- What do you get when you run `locate ntdll.dll.so`? For reference, I get:
  ```
  $ locate ntdll.dll.so
  /opt/wine-devel/lib/wine/ntdll.dll.so
  /opt/wine-devel/lib64/wine/ntdll.dll.so
  ```
  This is with `wine-devel` 3.9 from WineHQ.
  

(Don't worry about the Keybase thing)

**Comment by isaiah36** [comment]
wine-3.0 (Ubuntu 3.0-1ubuntu1)
Ubuntu Mate 18.04 64bit
/usr/lib/i386-linux-gnu/wine/ntdll.dll.so
/usr/lib/x86_64-linux-gnu/wine/ntdll.dll.so

**Comment by aljelly** [comment]
I updated my comment with the scripts, it should work for you now. In step 1, use the first code snippet.

**Comment by falkTX** [comment]
@aljelly please stop posting links to random third-party binaries

**Comment by isaiah36** [comment]
The files were registered successfully. I added the library override for wineasio in winecfg. But it does not show up as an output option in Foobar 2000. I might as well wait for the KX version compatible with Ubuntu 18.04.
Thanks for the effort, aljelly! I appreciate it very much.

**Comment by isaiah36** [comment]
I successfully installed and registered the wineasio-amd64 but it does not show up presumably because Foobar is a 32bit app. The 32bit gives an error from Synaptic "Could not apply changes! Fix broken packages first."
I have only 2 repos, so that may be why.
http://ppa.launchpad.net/kxstudio-debian/ubuntus/ubuntu bionic main
http://kxstudio.linuxaudio.org/repo/ stable free
Do I need other repos besides these?

TIA

**Comment by falkTX** [comment]
I am reworking the kx repos, wine and general applications are no longer supported 
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
