### ISSUE TITLE
bug in latest linuxampler-lv2/vst

### ISSUE THREAD

**Issue by varpa** [KXStudio/Repository#130]
I find that latest linuxsampler-lv2/vst (2:2.0.0+svn3347-1kxstudio1)  have a strange problem of playing release samples too loud so a buzzing is heard after releasing a key.  Of course release samples depend on the sample library loaded.   For example, I commonly use the SampleTek TBO gigasampler piano and this problem is quite noticeable.   I've attached an audio sample of some notes played with TBO which show the problem, followed by same notes without the problem.   The problem does not occur if TBO is loaded directly in linuxsampler (with qsampler) or with carla, but DOES occur when lv2 or vst linuxsampler plugin is used.  I know the problem is with the release samples because with TBO there is a "no-release" sample that can be loaded and this does not have the problem (of course does not sound good because of lacking release samples).   I "fixed" the problem by downgrading to linuxsampler-lv2/vst version 1.0.0+svn2593-1kxstudio3 (which was the only previous version available).  (TBO.zip contains TBO.mp3)
[TBO.zip](https://github.com/KXStudio/Repository/files/1377848/TBO.zip)

**Comment by falkTX** [comment]
linuxsampler code is too complex for me to even attempt to fix anything.
please report the issue upstream. when fixed let me know and I'll update the linuxsampler packages.

**Comment by ahellquist** [comment]
Hi

I am quite ceratain that Linuxsampler have had nonworking or buggy release
sample handling for a very long time and lately it has been fixed to work
as supposed.
I think there is an option to enable the old buggy behavior but as said.
The bug is finally fixed Don't remeber if this was only affecting SFZ or
Giga libraries but this might be a clue to why things behave differently.

(Anders

2017-10-13 9:48 GMT+02:00 Filipe Coelho <notifications@github.com>:

**Comment by falkTX** [comment]
Linuxsampler stuff has been updated in the kx repos.
Please get all updates and check if the issue still remains.
Thank you.

**Comment by varpa** [comment]
I upgraded to the latest linuxsampler and the bug is gone.   Thanks for packaging the new version.

**Comment by falkTX** [comment]
Good to know.
And thanks for testing.
