### ISSUE TITLE
Unnecessary Jack2 dependencies

### ISSUE THREAD

**Issue by varpa** [KXStudio/Repository#132]
I'm using kxstudio repos in AVLinux which by default uses Jack2.   However, with my firewire device (Focusrite SaffirePro24) I find that Jack1 works better.  However, many audio programs are inexplicably dependent on Jack2, so that when you try to install them, synaptic wants to remove Jack1 and install Jack2.   Some examples of this are: clementine, hydrogen, sooperlooper, pulse-jack connection.    Why are there such dependencies and is there any workaround to avoid them? 
Can the dependencies be changed to require only Jack and not specifically Jack2?

**Comment by falkTX** [comment]
I don't see these dependencies myself, in fact it should be the other way around if this was exactly the issue, since libjack0 is JACK1, so JACK1 ends up being the default in debian based systems usually.

this is tricky the way debian sets it up, but using apt-get manually might work, ie:
`sudo apt-get install libjack0 jackd1 hydrogen`

**Comment by varpa** [comment]
I tried you suggestion but it did not work:

# apt-get install libjack0 jackd1 hydrogen
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libjack0 is already the newest version (2:0.124.2~20151211-2~xenial1).
libjack0 set to manually installed.
jackd1 is already the newest version (2:0.124.2~20151211-2~xenial1).
jackd1 set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hydrogen : Depends: libportaudio2 (>= 19+svn20101113) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Tried to install clementine and got a different problem:
# apt-get install libjack0 jackd1 clementine
.... skipping ...
The following packages have unmet dependencies:
 clementine : Depends: gstreamer1.0-plugins-good but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

In AVLinux some packages are held, maybe that is the source of the problem ?

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back

both hydrogen and clementine are not part the new repos. and most applications anyway.
this is a general issue with debian/ubuntu rather than kxstudio.
