### ISSUE TITLE
[package request] update MusE to the latest 3.0

### ISSUE THREAD

**Issue by chaocrator** [KXStudio/Repository#156]
since MusE 3.0 is out, please update package to the latest.
currently packaged MusE 2.2 does not even start on many modern systems.

**Comment by falkTX** [comment]
Yes, I saw the news and know about old version not starting.
Will update its package soon.

Note though that launchpad is not taking any new package builds at the moment.
I suspect they want to wait till meltdown/spectre situation is under control first.

**Comment by chaocrator** [comment]
you're right, i think.
https://mobile.twitter.com/launchpadstatus/status/948688233029881856

**Comment by chaocrator** [comment]
they are back 
https://mobile.twitter.com/launchpadstatus/status/951339462092443648

**Comment by lrfinotti** [comment]
I'd like to second this request!  Thanks for your consideration.

**Comment by a13** [comment]
any news here?

**Comment by falkTX** [comment]
not really.
muse is progressing well, it deserves an update for sure.

I have to do some preparations for 18.04 and a new repo setup.
14.04 is getting EOL, but I dont have time now to handle it.

sorry for taking so long, later in the year we should have kxstudio repos handled much better.
Since I have to restructure the way they work, I will make sure things are easier to manage this time.

**Comment by a13** [comment]
the thing is old versions don't work at all (at least for me), so I had to build it from the Disco specs myself.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
For muse, I recommend to switch over to the new repos, remove the kxstudio package of it, and reinstall it again (which will be non-kxstudio version now)
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
