### ISSUE TITLE
Pulseaudio removes wine32

### ISSUE THREAD

**Issue by korakios** [KXStudio/Repository#157]
Hi,
I am on Debian stretch with KXStudio repositories enabled ( avlinux )
pulseaudio update tends to remove wine32 packages and don’t allow wine-rt either .

**Comment by singformegospel** [comment]
Hi, I seem to have a similar problem here. Can install wine but wine32 is missing and not installable. Problem remains after removing pulseaudio though.

**Comment by AVLinux** [comment]
Hi,

Part of the issue here is that Debian has PulseAudio '10' and KXStudio has on older version '8' but the KX package names have an 'epoch' in them which identifies the KXStudio packages as 'newer' when they actually aren't and the Debian Wine packages in AV Linux want PulseAudio 10 from Debian to satisfy the Wine32 dependency.

I'm curious why KXStudio has custom packages of PulseAudio when Debian and Ubuntu already provide current decent packaging for it?

**Comment by falkTX** [comment]
You must have the "ubuntus" PPA by mistake, the PPA that is supposed to be enabled for Ubuntu systems only.
This one has a custom pulseaudio package, so that normal pulseaudio installs bring the pulseaudio-module-jack package.
It's not safe to use this PPA on Debian systems, one reason being what you describe.

Run this:
```
# I need the output of this first command
ls /etc/apt/sources.list.d/kxstudio-debian*ubuntus-*.list
# Delete non-debian repo
sudo rm /etc/apt/sources.list.d/kxstudio-debian*ubuntus-*.list
sudo apt-get update
```

I will push a kxstudio-repos update that will try to force this more strongly.

**Comment by AVLinux** [comment]
Hi, apologies for the late response..

Here is the output of that command:

```
isotester@avl64box:~$ ls /etc/apt/sources.list.d/kxstudio-debian*ubuntus-*.list
/etc/apt/sources.list.d/kxstudio-debian-ubuntu-ubuntus-wily.list
/etc/apt/sources.list.d/kxstudio-debian-ubuntu-ubuntus-xenial.list
/etc/apt/sources.list.d/kxstudio-debian-ubuntu-ubuntus-yakkety.list
isotester@avl64box:~$ 

```

**Comment by falkTX** [comment]
I see, that was the issue all along.
Those repos should never have been added, I tried to correct it now on the latest kxstudio-repos package.
Do an update, then "apt-get update" again and see if it's still an issue.
Might be worth checking in synaptic if there are any "local" packages, that would be stuff coming from that repo we just removed.

**Comment by AVLinux** [comment]
Hi and thanks!!

A test on a fresh install of AV Linux 2017.4.9 confirms that both the updated kxstudio-repos (and gcc5) packages and removal of the unwanted Ubuntu package lists fixes the wine32 removal problem.
