### ISSUE TITLE
Repositories down

### ISSUE THREAD

**Issue by COLABORATI** [KXStudio/Repository#160]
Repos are down. The whole linuxaudio.org website seems to be down.

Also please add some monitoring infrastructure and a load balancer or proxy like e.g. haproxy that uses a different server when server one is down. A repository is too important to just have it on one simple server.

**Comment by erwan35** [comment]
Hello,

It seems that the box has been compromised:

https://linuxmusicians.com/viewtopic.php?f=4&t=18124

Cheers
Erwan

**Comment by COLABORATI** [comment]
hmm, then it should be published on all channels to take the repo out of any apt config asap - this shold happen right now. Please inform everybody to remove the repo from its computers!

**Comment by falkTX** [comment]
what? why?
it's a minor inconvenience for a service you get for free.
Just have a little patience, the service will be back online soon.

And the main repos still work fine (because they're are on launchpad).
Only the external repos, which contain basically ardour and wineasio, are offline at the moment.

Load balancers and other fancy features are out of scope for a hobby project like kxstudio.

**Comment by falkTX** [comment]
website and full repos are back up once again.
