### ISSUE TITLE
Please publish build scripts and howtos for this repo so we can decentralize the creation process

### ISSUE THREAD

**Issue by COLABORATI** [KXStudio/Repository#161]
Hi, it would be great if you would like to publish the parts that create the repo and build the packages, so we can help you with the many repetitive tasks of building the softwares. Also some more decentralization will be good, I feel it is too much bus factor having just one person maintaining the repo. 

Also a good detailed description about the repo building project would be very nice to have, plus explanation how to analyze build problems. I am sure many people would like to help you to keep the repo up2date and it will be good sharing of important knowledge, too! It will take some time to build a team of repo managers, but it will make this project a reliable global long term source for all linux audio enthusiasts.

**Comment by falkTX** [comment]
The main repos are on launchpad, https://launchpad.net/~kxstudio-debian.
I use the usual methods for uploading packages there, nothing too fancy about it.
The setup I use is a little unusual - using a single ubuntu version with static libs so that packages are generic enough to be usable everywhere - but it still ends up being regular PPAs.
ie, uploading uses something like `dput kxstudio-debian/libs *.changes`.

The external repo scripts are published in this repository.
There's the download packages, recreate repo and update repo.
For a local repo instance, you only need to download the packages and then keep running update-repo when stuff is updated.
The actual files are stored in github, in releases for this repo.

I'd be grateful to have someone else join in the efforts of the packaging, but as I see it, if someone was really interested they would contact me saying so.
Having documentation out there on how it works would be more stress for me, as I would have to keep the document in sync with any random change I need to do on the repos.

Also, consider that real packagers might prefer to submit something to debian directly, not to kxstudio.
The list of to-do packages has been increasing a lot recently, but it's mainly because I have been focusing on other stuff first (Carla, and now going to be plugins, then KX ISO).

**Comment by COLABORATI** [comment]
Why are there so many apt sources and not just one repo source? I do not understand how that happens, what is the reason for that. Couldn't you just publish one ppa?

**Comment by falkTX** [comment]
The main reason for more than one is to keep the per-repo storage below 2Gb (launchpad default limit).
Going above 2Gb means asking for permission (they bump it to 3Gb if the project seems in good stance and has a reason for it). Then after reaching 3Gb you need to ask for an increase again...
From the start I knew the PPAs would need a lot more than 2Gb, likely 10Gb in total.
So I separated them to avoid needing to ask them, waiting for approval (and perhaps could be denied) and all that.

There are other repos which need to be separate because they build different things.
The "toolchain" one for example is meant for build stuff, it's not meant for end-users.
The gcc5/gcc5-deps are meant for users in newer distros, they should not be added for "old" users.

The separation also makes it easier for me to keep track of things.
I know where apps, plugins and libs are. The list of packages per PPA does not get enormous, for helps me a little in its maintenance.

The external repo is needed because launchpad does not allow pre-built binaries, and also has issues compiling stuff against wine.
So for this the external repo includes ardour (pre-built package from upstream), and a few wine related things.

**Comment by falkTX** [comment]
hopefully that answers the question. closing this specific issue now.
