### ISSUE TITLE
pd pulp lv2

### ISSUE THREAD

**Issue by erwan35** [KXStudio/Repository#163]
Hello,

I'm under the impression that the pd pulp lv2 plugins are not working since the recent upgrade (2:20180211-1kxstudio2). Not sure whether it was working before in fact...

Ardour is complaining:
[WARNING]: Ignoring LV2 plugin "Pd Pulp" because its buffer-size requirements cannot be satisfied.
[WARNING]: Ignoring LV2 plugin "Pd Pulp FX" because its buffer-size requirements cannot be satisfied.

No prob with the vst plugins.

Is this supposed to be reported to the upstream ? 

Cheers
Erwan

**Comment by falkTX** [comment]
this is intentional, those plugins are not made to run with variable buffer sizes.
there's just no way to report that in vst, only in lv2.
if you run the vst and automate a parameter or use loop points in ardour, the plugin will get trigger xruns or worst case crash (including ardour itself).
as protection, I disable variable buffer size for these plugins. (the same applies to klangfalter and vex)
