### ISSUE TITLE
please stop diverging from mainstream debian, use backports

### ISSUE THREAD

**Issue by COLABORATI** [KXStudio/Repository#179]
please stop fragmenting the much-too-small linux audio world - please go mainstream and become a debian maintainer, add your packages to debian. after watching this for some time I come to the (obvious) conclusion that it is not possible for one person or a small team to maintain a whole distro - please stop doing that. 
add your packages to debian and start with debian backports, thanks.

really - you started somehow with the right idea, but still you get into unmaintainability zone because of too many distros. Stop supporting Ubuntu, they are breaking the linux world too many times. 18.04 is catastrophic. Use debian and add what you think is cool, but keep it compatible with debian releases, this will be the only way to avoid a broken situation like it is now  and with one bazillion static packages that do not run on different things. use the mothership! please!

This is really like five people in a tiny space ship starting to discuss about which direction to take - we can not afford that. Linux people need to stop with their egoisms and realize that it is time to build on that one thing to make the final step into 'linux on desktop'. The fragmentation is a ridicolous self-destruct going on and even the most talented guys like you can not keep up with the diversity and end up making niche products.

Debian gives us everything, the infrastructure is here - you just need to use it. Please rethink your strategy, thanks.

I write this because I am very sad about the situation in 2018. Linux devs need to find a way to unite, thanks!

**Comment by AstralStorm** [comment]
I do not agree with the top poster. About the only mainstream distro that cares about realtime audio is Ubuntu Studio. So please do keep supporting that.

**Comment by christianwn** [comment]
@AstralStorm Debian has the most crucial part in place, ready to use, the rt-kernel. The low latency kernel is not good enough. There is nothing wrong with UbuntuStudio, but I do not reason as you do. Bleeding edge on audio is in my world a big no no, that is because of stability. The core system should not be changed much, new versions and stuff, and bleeding edge only added for missing features or workarounds. Sadly there is no standard way to optimize a linux distro for audio, this is more like an art in it self. I do prefer to do it my self, but it takes so much time...
Debians mission is not pro audio or realtime systems. Debian stretch is of the stable flavor and this is tremendously important. When you tweak you need to be able to trust your system, else you can end up going in circles forever. 
If the maintainers of audio related distros and programs could add their effort directly into the debian eco system and focused on modifying on top of debian stable, then you would get the best of both worlds. There would not be wasted effort. Audio team do pro audio mod for debian and debian team do well debian. I already see FalkeFX doing a lot of extra work getting the kxstudio packages working with kde neon, but there are really more important work to do with the kxstudio programs... I even told him how to get a 5-10% performance increase in jackd by using cpu isolation, he does not even have the time to read my freely given great tips. I donate to the work he does and I have the best intentions, guess how that feels...
There is so much to do, too much for most people, we need to reduce unnecessary work to a minimum.
Last, if you want to support an audio distro go help out and donate to haiku, they hold the future to a great media os, not linux. (That is not intended as disrespect)

**Comment by Lyberta** [comment]
What is wrong with vanilla Debian? I've been using it entire time and haven't had problems with it.

Anyway, I think most of the apps can be packaged as Flatpaks. That way we don't have to depend on Debian at all and be distro-agnostic.

**Comment by falkTX** [comment]
The applications can be packaged in many ways, but not the plugins.
Plugins need to be self-contained, which is almost never the case in regular distributions.
Plus, because of performance, we need to at least enable SSE2 in audio plugins (which together with fast-math option, can get rid of denormals). Debian still does not do so, since it wants to keep support for very old machines.
And finally, quite a few packages are built in a non-optimized way, reducing performance.
Until some years ago, qtractor was being built with debug mode on by default (maintainers did not know the difference between full debug mode vs stripping away debug symbols into separate package)
Regular users will not do debugging, I feel it is quite pointless to try to get debugging stuff into packages at the cost of performance.

Anyway, going forward the kxstudio repos will stop having applications and focus mostly on audio plugins.
