### ISSUE TITLE
package request: Guitarix update

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#191]
https://linuxmusicians.com/viewtopic.php?f=47&t=17028&start=135#p94778

says

> Guitarix ain't depend on a special version of libcurl, and work with both.
> You could build it against libcurl3, and it still work with libcurl4! (I've just done exactly that.)
> Both libcurl (3 + 4) versions provide "libcurl.so.4" which is used for linking.
> All you need to do is using in the dependency field of the package "libcurl3|libcurl4" instead only one version, then the version installed will be used

**Comment by falkTX** [comment]
it is not that simple.. but I will update it soon anyway.
we will deal with issues of libcurl as they appear

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back

even though guitarix provides plugins, it also has an application that is not so simple to build.
the libcurl dependency is specially problematic.
debian has the guitarix package including both standalone application and the plugins, so even if I wanted to update only the plugins, that is not possible.
because of this, I will not have guitarix in the new repos.

I recommend to switch over to the new repos, remove the kxstudio package of guitarix, and reinstall it again (which will be non-kxstudio version now)
