### ISSUE TITLE
Package Request: Audacity (update + wxgtk2 build)

### ISSUE THREAD

**Issue by falkTX** [KXStudio/Repository#2]
Audacity needs some well deserved update, specially for the LV2 (+UI) support.
Also some distros build it with wxgtk3, which Audacity devs don't really like...
KXStudio can get the definitive build if it uses wxgtk2 and has LV2 support.

**Comment by milasudril** [comment]
There is a bug report posted here: https://bugs.launchpad.net/ubuntu/+source/audacity/+bug/1487811

**Comment by AVLinux** [comment]
Hi. This is still broken in Debian testing for months already which is still at 2.0.6+b3 (as of this post) and packages from the Ubuntu PPA will not work in Debian because of unmet dependencies. Audacity should not require packaging by a 3rd party packager but in this case it is not and has not been functional in Debian for quite some time, even with bug reports... Please consider packaging it with the correct 2.8 version of wxwidgets even though you shouldn't have to :/.

**Comment by wolftune** [comment]
Update: Audacity is already at 2.1.2 in Ubuntu 16.04 at least. I don't know if the wxgtk3 thing is an issue though. Also 2.1.3 is now out with some nice fixes…

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
