### ISSUE TITLE
Ardour under Debian Testing 2020

### ISSUE THREAD

**Issue by marcscama** [KXStudio/Repository#238]
Hi,
when i lunch Ardour it take take 5 minutes to open and is slow.
The Ardour package is in the https://kx.studio/repo/ gcc5 but on the site is write:
# Remove legacy repos
sudo dpkg --purge kxstudio-repos-gcc5.
I don't have this repository.
I don't have logs for you...sorry.
Best regards
Marks

**Comment by falkTX** [comment]
all is fine not having the legacy repos.

If ardour is slow, then try disabling checking for plugins.
The build in kxstudio is exactly the same as the "commercial" build of ardour, so it is known to work and used by many people.

**Comment by marcscama** [comment]
Hello 
Thanks for thé message.
Something is strange for me because if remove thé legacy repos i dont have ardour anymore because is only inside thé gcc5 repo. 
Ardour is put normally where, in thé app repo launchpad  like cadence?
Maybe is thé compiler debian have gcc10 now....

Thanks

**Comment by ahellquist** [comment]
I enabled kxstudio repos on my Ubuntu Studio a few weeks ago and after
upgrading the suggested updated kx packages (I was running Ubuntu Studio
20.04 so most things should be fairly new) my launch of ardour whent from
between 1-1.5 seconds to close to 40 seconds.

This is with the kxstudio upgraded Ardour 5.12. Running any of the nightly
builds from ardour is fine.. starts in 1 second.

Launching Ardour from console reveals that it complains a lot with
Fontconfig Warnings and errors and at the end it stalls at: Fontconfig
Error: Cannot load default config file

Maybe this is exactly what you too are experiencing ??

Regards, Anders

Den ons 20 maj 2020 kl 16:43 skrev marcscama <notifications@github.com>:

**Comment by falkTX** [comment]
It might be that we need a new ardour build.
But Ardour version 5 is not getting that, not with version 6 so close to final release.

Let's reevaluate this issue once Ardour 6 is out, by that time I will update the kxstudio version to match.

**Comment by marcscama** [comment]
Hello,
Something is wrong with kx package because i dont have issue with others binary.
Maybe but is just an stupid opinion thé problem is thé gtk2 version instead of gtk3
But for thé moment i don't know
Bye
mercredi, 20 mai 2020, 04:58PM +02:00 de Anders Hellquist  notifications@github.com :

**Comment by ahellquist** [comment]
Yes, No need to fix this but there seems to be a difference between Ardour
5.12@ubuntu and the kxstudio version. It was a rather big difference.

On another note

Regarding Carla and not being able to open GUIs from the patch-panel
view... That is a bigger problem than I first thought.

Imagine having a 24 channel audio interface (as I do) and many different
synths patched in carla with various efx chains (per synth instance) and
all or many of them have a tape plugin called tape. Until recently, I could
just go to the correct tape plugin and change stuff and know that it was
the correct instance of the tape plugin.

Now I have to switch to the rack-view and possibly scroll to find one of
many tape plugin instances and nothing distinguishes them other than a
small number... I might have to play on my keyboard to check which of all
the plugins react to the signal to be sure i adjust the correct one of (22
instances) and that might not be possible in a live gig session since
people do not expect someone making random noice just to find the correct
plugin.

I heavily make use of the midi-filter plugin to be able to connect multiple
midi controllers to this setup.

I write this not to complaint but more to give a picture of the rather big
regression this is (at least for me)

Thanks anyway for everything you do and take this as a user feedback for
coming decisions

Best regards, Anders


Den ons 20 maj 2020 kl 17:07 skrev Filipe Coelho <notifications@github.com>:

**Comment by falkTX** [comment]
>  Now I have to switch to the rack-view and possibly scroll to find one of many tape plugin instances and nothing distinguishes them other than a small number... I might have to play on my keyboard to check which of all the plugins react to the signal to be sure i adjust the correct one of (22 instances) and that might not be possible in a live gig session since people do not expect someone making random noice just to find the correct plugin.

this issue is not regarding carla.
but anyway, this issue is due to carla using some features present in a more recent jack2 version that ubuntu provides.

UbuntuStudio backports has an updated jack2 in 20.04
https://help.ubuntu.com/community/UbuntuStudio/BackportsPPA

**Comment by falkTX** [comment]
The repos that contain the ardour separate package have been removed/disabled.
I will write more details on the next kxstudio monthly report.
