### ISSUE TITLE
kxstudio-recommended-graphics fails with conflicts around GIMP

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#249]
I'm using KDE Neon latest. Verified in a couple different installs, the kxstudio-recommended-graphics fails due to some dependency conflict with something in Gimp. I can install Gimp itself separately and several of the plugins, but this conflict blocks the install of kxstudio-recommended-all as well as the graphics recommends.

**Comment by alignwaivers** [comment]
@wolftune There are are a number of installation targets that aren't directly in the ppa for some reason. My suggestion is next time try installing the exact package with a dependency problem (whatever subset/requirement of the kxstudio-recommended-graphics, in this case:, it narrows down the problem more (and if I recall the top level issue was gimp-ufraw, which had no candidate)


I downloaded and used dpkg to get the missing packages working (I think this was all of them): I believe this is the order necessary, all files were amd64 and downloaded from packages.ubuntu.com, and mostly it was just also-absent packages that were dependencies of gimp-ufraw
> libexiv2-14
libgtkimageview0
ufraw-batch
ufraw
gimp-ufraw

There's some messiness because it kxstudio-recommended-all (I assume your original target as well) succeeded to install an older version of ardour (I have 6.3), which took over the command line for ardour (which fails to run), but the new version still runs via the desktop properly... when I try to uninstall ardour:
>Investigating (0) kxstudio-recommended-audio:amd64 < 6.1.6 @ii mK Ib >
Broken kxstudio-recommended-audio:amd64 Depends on ardour:amd64 < 2:5.12.0-1kxstudio2v5 @ii pmR >
  Considering ardour:amd64 10001 as a solution to kxstudio-recommended-audio:amd64 1
  Removing kxstudio-recommended-audio:amd64 rather than change ardour:amd64
Investigating (0) kxstudio-recommended-all:amd64 < 6.1.6 @ii mK Ib >
Broken kxstudio-recommended-all:amd64 Depends on kxstudio-recommended-audio:amd64 < 6.1.6 @ii mR >
  Considering kxstudio-recommended-audio:amd64 1 as a solution to kxstudio-recommended-all:amd64 0
  Removing kxstudio-recommended-all:amd64 rather than change kxstudio-recommended-audio:amd64

Not gonna sort this out immediately as I don't think the vestigial ardour will be too much of an issue, and things are working for now.

Thanks for all things kxstudio!
(p.s. I'm curious why a gimp plugin is necessary for kxstudio stuff? - intriguing)

**Comment by wolftune** [comment]
>  (p.s. I'm curious why a gimp plugin is necessary for kxstudio stuff? - intriguing)

KXStudio recommnded meta packages aren't necessary at all. They are just quick ways to get recommended stuff, and Gimp and plugins are just multimedia-creativity stuff that @falkTX decided to recommend.

**Comment by falkTX** [comment]
I am removing the recommended packages, it is very hard to make them work with non-kxstudio provided packages as they can change at anypoint.
Done as per b653f2d4ea291a41e7cd85b0d5b61047f330b545
