### ISSUE TITLE
Freshen up some key packages?

### ISSUE THREAD

**Issue by AVLinux** [KXStudio/Repository#253]
Hi,

AV Linux has been using the KXStudio repositories for several years now and it has been a great resource for Plugins etc. so first let me reiterate my thanks for these valuable repos and applications! It has become apparent that some common key applications (ie Guitarix, Qjackctl to name a couple) are getting some age on them. Would it be possible to freshen up some of the popular and common applications? I don't suggest necessarily every point release, as an example guitarix is at 0.36 and it's current release is at 0.41, even every other release would be valuable..

**Comment by falkTX** [comment]
Hi there!

Since I brought back the repositories, I have been focusing on plugins only.
The 2 you mention are not in the repos, as can be seen in https://kx.studio/Repositories:Applications

I am a bit behind on plugins, but only by a few months max as far as I know..

**Comment by AVLinux** [comment]
OK, Well I guess I missed the memo on that, so thanks for letting me know.

**Comment by falkTX** [comment]
hmm I recommend to keep an eye on https://kx.studio/News/ then, there is an RSS feed.
or just the linuxaudio planet, where those posts end up in too.

The details about the repositories were written in detail when I started working on the repos again.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
(the whole changes to require 18.04 / buster situation)

**Comment by AVLinux** [comment]
Got it!

No problem, it was me who missed it.. Thanks for all the great work on the Plugins, it is very much appreciated. I will figure out the other stuff now that I'm aware of the situation.

**Comment by falkTX** [comment]
Please note that contributions are very welcome.
I can guide you through the PPA upload process, and the usual rules I follow for uploading.

**Comment by falkTX** [comment]
not sure what to do about this ticket.
I understand the need to have a few applications more up-to-date, but I restrict myself to mostly plugins now in order to stay sane and not so much overworked.

I have been updating a few things lately. adlplug, zam-plugins, lsp-plugins, drumgizmo.. 
I am always open to contributions and helping hands.

For now I will close this issue.
If you need something in specific, please open a ticket per package. qjackctl is something simple that I could add, if that is really necessary, guitarix not so much as it is very big application with lots of dependencies, hard to do a generic package for it. I can separately package the ladspa and lv2 plugins though, been thinking about it already...
