### ISSUE TITLE
Repositories from deb packages have old codename in Ubuntu 20.04

### ISSUE THREAD

**Issue by spectrumIG** [KXStudio/Repository#283]
Doing a  fresh installation  from deb packages installs repo with old 18.04 codename instead of new focal. 

Packages taken from official website.

Would it be possibile to change and update the codename?

**Comment by falkTX** [comment]
That is normal and expected.
KXStudio builds with 18.04 as base in order to make it work on there and up, so it works on Ubuntu 18.04, 20.04, 20.10, etc, same for other Debian derivatives. 18.04 is good enough to work as base and not old enough.
The KXStudio packages are mostly statically built, so their base system doesn't matter in the end.
