### ISSUE TITLE
Access forbidden on launchpad.net

### ISSUE THREAD

**Issue by lucmp** [KXStudio/Repository#289]
I am unable to access launchpad.net and update a package from Synaptic. The error message says it's forbidden. Is it shut down or is it something on my end?

![forbidden](https://user-images.githubusercontent.com/2882969/167989319-f8d05e0a-9a65-4802-bc57-6dd30bca17e1.png)

**Comment by falkTX** [comment]
not really forbidden, these are old already deleted files.
I suggest you to purge and reenable the repos.
See https://kx.studio/Repositories:FAQ for details

**Comment by lucmp** [comment]
Hi. Thank you for your reply.

I read the page you referred me to and I am still unsure of what to do. The problem is, I'm still on Debian Stretch and I really can't afford to upgrade anytime soon. I have my reasons. It's complicated. By that page, it seems that Debian 11 is required now. So I'd like to add two questions here:

1) Are you sure that purging kxtudio-repos (what about kxstudio-repos-gcc5?) will not affect other packages? I don't want to lose anything.

2) Should I even bother? I mean, are there any Debian Stretch packages still available?

(Less relevant: qtractor has one nasty bug that always prevented me from using it. I would like to test a new version, maybe that bug has been fixed.)

**Comment by falkTX** [comment]
Due to reasons I explained in https://kx.studio/News/?action=view&url=changes-in-kxstudio-repositories-2 I have moved to newer base and stretch as distro is no longer supported.
That makes things complicated for you yes, if you really need to stick with stretch as distro then best is to avoid trying to change anything for now.

tbqh, I hate this thing of always moving, always updating to new thinngs way that software and distributions push for. but it is out of my control too, so I need to also keep things updated and changing just to keep stuff working..
