### ISSUE TITLE
Request: Compile lv2-dev package with the old_headers option set -- can not compile Ardour

### ISSUE THREAD

**Issue by lasutek** [KXStudio/Repository#303]
Current version of the kxstudio lv2-dev package \(lv2  6:1.18.10-1kxstudio2  falkTX \(2023-04-22\)\) seems to be compiled without the `old_headers` option set, which causes problem when compiling Ardour. Ardour expect to find a include directory structure like "lv2/lv2plug.in/ns/..." .

See [LV2, Headers](https://gitlab.com/lv2/lv2)
>The lv2/ include namespace is reserved for this LV2 distribution.
>Other projects may extend LV2, but must place their headers elsewhere.
>Headers are installed to includedir with paths like:

>\#include "lv2/urid/urid.h"
>For backwards compatibility, if the old_headers option is set, then headers
>are also installed to the older URI-based paths:

>\#include "lv2/lv2plug.in/ns/ext/urid/urid.h"
>Projects still using this style are encourated to migrate to the shorter style
>above.

**Comment by falkTX** [comment]
enabling that option causes issues for package updates, because they used to be a files and now are symlinks.

it is also legacy as the name says, so eventually to be removed altogether from lv2 installs.
I much rather break things early, we simply need to adjust the broken software to use the proper headers.
