### ISSUE TITLE
package request: Mixxx 2

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#34]
would be ideal to include the new v2 in KXStudio repos even though it's available easily from Mixxx ppa

**Comment by stragu** [comment]
Since this issue was created, Mixxx 2.1 came out and it just saw its [second bugfix release (2.1.2)](https://mixxxblog.blogspot.com/2018/08/mixxx-2.html), so I'd say everyone would benefit from a newer version that is getting more attention for stability.

Currently, 2.0.0 is in the Ubuntu 18.04 repos.
I just added the [Mixxx repository](https://launchpad.net/~mixxx/+archive/ubuntu/mixxx) on Ubuntu Budgie 18.04 and version 2.1.2 works as expected.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
