### ISSUE TITLE
Guitarix LADSPA's with undefined symbol errors in Ardour and Mixbus.

### ISSUE THREAD

**Issue by AVLinux** [KXStudio/Repository#92]
Hi,

For quite a while this message has appeared in the log window when launching Ardour and Mixbus bundles even with the latest updated Guitarix packages installed and updated:

[ERROR]: LADSPA: cannot load module "/usr/lib/ladspa/ladspa_guitarix.so" (/usr/lib/ladspa/ladspa_guitarix.so: undefined symbol: _ZN4sigc9slot_baseC1EOS0_)

Seen using the KXStudio gcc5 repos on AV Linux 2016 (Debian Stretch).

**Comment by m4l3z** [comment]
Confirmed and reproduced under Linux Mint 18.1 with KXStudio gcc5 repos.

**Comment by tonilink** [comment]
Same using Kubuntu 17.04, Ardour 5.10, KXStudio gcc5.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back

even though guitarix provides plugins, it also has an application that is not so simple to build.
the libcurl dependency is specially problematic.
debian has the guitarix package including both standalone application and the plugins, so even if I wanted to update only the plugins, that is not possible.
because of this, I will not have guitarix in the new repos.

I recommend to switch over to the new repos, remove the kxstudio package of guitarix, and reinstall it again (which will be non-kxstudio version now)
